apiVersion: storage.halo.run/v1alpha1
kind: PolicyTemplate
metadata:
  name: easy-giteeoss
spec:
  displayName: Gitee OSS
  settingName: giteeoss-form-setting
---
apiVersion: v1alpha1
kind: Setting
metadata:
  name: giteeoss-form-setting
spec:
  forms:
    - group: default
      formSchema:
        - $formkit: text
          name: owner
          label: Gitee账户空间名
          validation: required
        - $formkit: text
          name: repo
          label: 远程仓库名
          validation: required
        - $formkit: text
          name: path
          label: 上传目录
          placeholder: 如不填写，则默认上传到根目录(请不要以"/")开头
        - $formkit: text
          name: branch
          label: 分支
          value: master
          placeholder: 仓库分支
          validation: required
        - $formkit: password
          name: accessToken
          label: Gitee授权凭证
          validation: required
        - $formkit: text
          name: haloUserName
          label: halo账户
          placeholder: 请填写当前halo账号
          validation: required
        - $formkit: radio
          name: ifDelSrc
          label: 是否删除源文件
          value: true
          options:
            - label: 是
              value: true
            - label: 否
              value: false
